name: Cypress Tests

on: [push]

jobs:
  single-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server -p 8080 # Zmienić na odpowiednią komendę do serwowania strony
          wait-on: 'http://localhost:8080' # Oczekuje na serwer lokalny
        timeout-minutes: 10
