name: Cypress Tests

on: [push]

jobs:
  single-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server -p 8080 
          wait-on: 'http://localhost:8080' 
        timeout-minutes: 10
       
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: /home/runner/work/TestingWebsites/TestingWebsites/cypress/screenshots